# Generated by Django 4.0.5 on 2022-07-07 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('is_revealed', models.BooleanField(verbose_name='Раскрыт ли реальный цвет')),
                ('color_guess', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(16777215, 'Превышен максимум для цвета')], verbose_name='Предполагаемый цвет в HEX')),
                ('color_actual', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(16777215, 'Превышен максимум для цвета')], verbose_name='Реальный цвет в HEX')),
            ],
        ),
    ]
